[modules]
[modules.mycow]
cow_type = 'Holstein'
enabled = true
name = 'cow'
repo_name = 'crossett'
version = 'v0.0.1'

[repositories]
[repositories.crossett]
url = 'https://raw.githubusercontent.com/crossett/altima-modules/main/modules/'

[user]
name = 'Jack Doe'
